name: Deploy Frontend to MilesWeb

on:
  push:
    branches:
      - main # Or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Production Bundle
        run: npm run build

      - name: Deploy dist files to ems.spikedace.com
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ""
          ARGS: "-rlgoDzvc -i --delete --exclude='.htaccess' --exclude='error_pages/' --exclude='dist.zip'"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: "~/ems.spikedace.com"
          PASSWORD: ${{ secrets.SSH_PASSWORD }}